### ISSUE TITLE
[TSK-57] - Create Model Class

### ISSUE THREAD

**Issue by blackgetter** [Intel-AI-academy/sParkTower#17]
### Issue 타입
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 의존성, 환경 변수, 빌드 관련 코드 업데이트

## Purpose
> 주차관리 타워의 MVC패턴 중 모델을 추가합니다.
## Job details
- [ ]

**Comment by Eun04** [comment]
Good job
